# @package _global_

trainer:
    name: 'NAF'
    ens_num: 2
    vf_kwargs: {
        hidden_cfg: {hidden_dims: [256, 256], hidden_act: 'ReLU',}
    } 
    mu_kwargs: {
        hidden_cfg: {hidden_dims: [256, 256], hidden_act: 'Tanh',}
    }
    L_kwargs: {
        hidden_cfg: {hidden_dims: [256, 256], hidden_act: 'Tanh',}
    }
    opt_kwargs: {
        opt_name: 'adam', 
        grad_clip: -1., 
        max_grad_norm: -1.,
        anneal: null, # if 'anneal' is not None, set it as the arguments ({'name':xx, 'arg1':xx, ...}) to build a 'Schedule'
        lr_kwargs: {
            learning_rate: 3e-4 # if 'anneal' is not None, 'learning_rate' should be assigned as a 'Schedule' 
        }
    }
    action_noise: 0.1
    reward_scaling: 10.0
    tau: 0.005
    discount: 0.99

    exp_prefix: "${env.backend}_norm=${env.obs_norm}_lr=${trainer.opt_kwargs.lr_kwargs.learning_rate}\
    _reward_scaling=${trainer.reward_scaling}\
    _discount=${trainer.discount}\
    _batch_size=${rlalg.batch_size}\
    act_noise=${trainer.action_noise}_seed=${seed}"
