# @package _global_

trainer:
    name: 'SAC'
    qf_kwargs: {
        hidden_cfg: {hidden_dims: [256, 256], hidden_act: 'ReLU',}
    }
    actor_kwargs: {
        hidden_cfg: {hidden_dims: [256, 256], hidden_act: 'ReLU'}
    }
    opt_kwargs: {
        opt_name: 'adam', 
        grad_clip: -1., 
        max_grad_norm: -1.,
        anneal: null, # if 'anneal' is not None, set it as the arguments ({'name':xx, 'arg1':xx, ...}) to build a 'Schedule'
        lr_kwargs: {
            learning_rate: 3e-4 # if 'anneal' is not None, 'learning_rate' should be assigned as a 'Schedule' 
        }
    }
    auto_finetune_temp: True
    init_temp: 0.2
    reward_scaling: 5.0
    discount: 0.99
    tau: 0.005
    target_entropy: null 
    
    exp_prefix: "lr=${trainer.opt_kwargs.lr_kwargs.learning_rate}\
    _reward_scaling=${trainer.reward_scaling}\
    _grad_clip=${trainer.opt_kwargs.grad_clip}\
    _max_grad_norm=${trainer.opt_kwargs.max_grad_norm}"






