project: 'JAXA-${env.type}-${trainer.name}'

seed: 0
num_seeds: 5 

wandb_mode: False
logger:
    log_dir: '/home/zhangzhe/all_logs/jaxa'

env:
    name: 'Breakout-MinAtar' # 'Asterix-MinAtar', 'halfcheetah-Brax'
    type: 'gymnax' # 'gymnax', 'Brax'
    backend: null # 'if Brax: generalized/positional/spring'
    expl_num: 1
    eval_num: 5
    obs_norm: False 
    obs_flat: False 
    # max_episode_steps: -1 # if >0, will set the max episode length, otherwise follow the default

buffer:
    max_replay_buffer_size: 100000

rl_paradigm: 'online' 

rlalg:
    batch_size: 32 
    start_epoch: 0 
    end_epoch: 500
    total_steps: 5000000
    num_eval_episodes_per_epoch: 5
    num_timesteps_per_epoch: 10000
    vec_env_rollout_len: 1 
    num_trains_per_expl_step: null
    min_num_steps_before_training: 5000


save_model: False

trainer: 
    dqn

spec: # specific config for some envs if needed
    null

hydra:
    output_subdir: null

defaults:
    - _self_
    - trainer: dqn
    - spec: null
    - override hydra/launcher: joblib





