project: 'JAXA-${trainer.name}-SS'

seed: 0
num_seeds: 6 

wandb_mode: True
logger:
    log_dir: '/home/zhangzhe/all_logs/jaxa'

env:
    name: 'halfcheetah-random-v2' # 'halfcheetah-Brax' / 'halfcheetah-random-v2'
    backend: null # 'if Brax: generalized/positional/spring'
    expl_num: 100
    eval_num: 5
    obs_norm: True 
    max_episode_steps: -1 # if >0, will set the max episode length, otherwise follow the default

buffer:
    max_replay_buffer_size: 1000000

rl_paradigm: 'online' 

rlalg:
    batch_size: 512
    start_epoch: 0 # offline epochs if negative 
    end_epoch: 100
    total_steps: 1000000
    num_eval_episodes_per_epoch: 5
    # online RL HP
    num_timesteps_per_epoch: 10000
    vec_env_rollout_len: 1 
    num_trains_per_expl_step: null
    min_num_steps_before_training: 1e4
    # offline RL HP


save_model: False

trainer: 
    sac

spec: # specific config for some envs if needed
    null

hydra:
    output_subdir: null

defaults:
    - _self_
    - trainer: sac
    - spec: null
    - override hydra/launcher: joblib





